### PR TITLE
read char

### PR DESCRIPTION
**Pull request by llop**
read can take 'chr' as type to read individual characters.
please review

### CODE REVIEW

**Comment by jordi-petit** [comment]
There must be a bug somewhere, as I had an error when executing `a = read(int)`.

**Comment by llop** [comment]
what error did you get?

**Comment by llop** [comment]
Made it python2-compatible. Can you please try again?

**Comment by jordi-petit** [comment]
Thanks, I did not realize your code was for Python3. If we can, let's have it compatible with Python2 and Python3.

**Comment by llop** [comment]
Awesome, thank you!

**Pull request merged**
